import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';
import { Box, Flex } from '@chakra-ui/react';
import Header from '../components/shared/Header/Header';
import SidebarNavigation from '@/components/shared/SidebarNavigation/SidebarNavigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className} style={{ backgroundColor: '#0D065E' }}>
				<Providers>
					<Header />
					<Flex justifyContent="space-between">
						<SidebarNavigation />
						<Box width="80vw">{children}</Box>
					</Flex>
				</Providers>
			</body>
		</html>
	);
}
